language: node_js
node_js:
  - '12'
  - '10'
  - '8'
install: yarn install
script: yarn test
deploy:
  provider: npm
  email: ops@craft.ai
  api_key:
    secure: dsFKyxv5VGacSslPf/aIk76XYT6s5YokZOl0n1MH5rrRJd4GkLJqB58tMPsRVab2STDDlRJZ8ttPn9bceI4QOv+MT+/mHJ7JIV1XcbxgGcKXgpy/JNMvjW/QROo36+rqnz3lyG777WndXRZvsxU0QvysTAQ/x28WUQqDB9OSHggZvThW4OqH12KU3/BrUuPyimQGgLd3hSLiuBq+tpCnqh0FOy3/WIBA35+mRc12sBIb7WmcY309bPa8rfZXiSNNUb3XxApAmD3B+Q7WpSS5V3fgwWK86lX7SF0KKyBy7LE65CWZF+2iAzkgWO7cGfFEf7ydj5ZegFPF3XZJCxmPAlhg6+Q/2RthJ/2A+zcFVjt1FDXErOfUTrraeLQUoPw7DmeJvCSbJ2JD/m+9rP+avwherbO9Ea/5xHhJaDe+eKO3z98qH6YTIy9hKLnKLnfcfVT3TyZs9ERSbWk1mKGRMPDByVVWKONRVOx6GhziX6sXhVUzvNWEZFJyCipPzJc4kNBprKLilPIOccQvEq624KquwvlUmZdf6EYQtoERChAzQnrx9WoYisS4iyi93gxhAzGegzAanxNuYkWSY+5g++jWFxR4+JiKrE9Kh7wdlo3aP+8dAmI9z2J4aBGDbKEisIM4cMONxIxBU99QNxwbIXxjZuT0uwY8rvIzByYwQWI=
  on:
    tags: true
    repo: craft-ai/alpes
    node: '8'
  skip_cleanup: true
