language: node_js
node_js:
- '8'
- '6'
install: yarn install
script: yarn test
deploy:
  provider: npm
  email: ops@craft.ai
  api_key:
    secure: kMYbBDgB9zU0pac5uolfoJ0bCZVHFfd/DYDv+vb9OHQeZUB+/O6GTdSEl6BSDTYio0GLKZo3qJEBTQ0Xz5HUsDLjUEwnoyV7z5OjOrhnPP2Nr5bGaWBfRWfnn7mwD/JBeaDyL9ClCPYDWejpgYzBaf1GRNmXY4SEvxX/khmRRb3nQOHQtMommhZXPnJ4GPAH/yGx+Gx8F7cOwGNaJOJilVhP7SUHAogBYxecKllTmIlFzmY93hSqCem49a39J540xVebXqNGswfvzx7Sw0uKgBTdIfWuro5FRlmNMj3hSIgUovRZJiwu5DRkQSfZCkcYjVjNrHxuLWfI1TEVHLkGxCTbv/gOqAJBLShVXY6X8sNNXtBPuEq+VRmPhkuabxVUkshglUDFM3hz7sgV9ROZ9E9VSg49sDivw7+jhVAKU7sYYzadPeRMfs5pG5twQH4oEEQgWbf734d6Zl3Kpfy5lUhTlQp2uZ4PAC0X4FZWEgs/JUx7gjSqB1UOYQWzydisz3/ToCr099S2USz3p9706VdOD5HiCOXeYevTlQknLD/EPCY3cB2kCVeSG54m+2TA4YrGZ4xHpfU8I1fA9Q2yjqVoGoEy8VY7hPq11xNVTBGMHpc2MINvRsXjqWWUiWpLsxqFVwGV459pY+MvJw2HcAjaxR3GwULCg0rP77EKq10=
  on:
    tags: true
    repo: craft-ai/alpes
    node: '8'
  skip_cleanup: true
